var grade_percents = {
    "Project": 40,
    "Presentation": 5,
    "Homework": 15,
    "Participation": 5,
    "Midterm": 15,
    "Final": 20
}

// From Kaggle Student datasets, with modifications
var drinks = [
  {
    "Beverage_category": "Coffee",
    "Beverage": "Brewed Coffee",
    "Beverage_prep": "Plain",
    "Calories": 5,
    "Total Fat (g)": 0.1,
    "Trans Fat (g)": 0,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 10,
    "Cholesterol (mg)": 0,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 0,
    "Protein (g)": 1,
    "Vitamin A (fDV)": 0,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 330
  },
  {
    "Beverage_category": "Classic Espresso Drinks",
    "Beverage": "Caff̬ Latte",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 130,
    "Total Fat (g)": 0.3,
    "Trans Fat (g)": 0.2,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 150,
    "Cholesterol (mg)": 19,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 18,
    "Protein (g)": 13,
    "Vitamin A (fDV)": 0.2,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.4,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 150
  },
  {
    "Beverage_category": "Classic Espresso Drinks",
    "Beverage": "Caff̬ Latte",
    "Beverage_prep": "2% Milk",
    "Calories": 190,
    "Total Fat (g)": 7,
    "Trans Fat (g)": 3.5,
    "Saturated Fat (g)": 0.2,
    "Sodium (mg)": 30,
    "Total Carbohydrates (g)": 170,
    "Cholesterol (mg)": 19,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 17,
    "Protein (g)": 12,
    "Vitamin A (fDV)": 0.2,
    "Vitamin C (fDV)": 0.02,
    "Calcium (fDV)": 0.4,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 150
  },
  {
    "Beverage_category": "Classic Espresso Drinks",
    "Beverage": "Caff̬ Latte",
    "Beverage_prep": "Soymilk",
    "Calories": 150,
    "Total Fat (g)": 5,
    "Trans Fat (g)": 0.5,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 130,
    "Cholesterol (mg)": 13,
    "Dietary Fibre (g)": 1,
    "Sugars (g)": 8,
    "Protein (g)": 10,
    "Vitamin A (fDV)": 0.15,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.4,
    "Iron (fDV)": 0.15,
    "Caffeine (mg)": 150
  },
  {
    "Beverage_category": "Classic Espresso Drinks",
    "Beverage": "Caff̬ Mocha (Without Whipped Cream)",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 220,
    "Total Fat (g)": 2.5,
    "Trans Fat (g)": 1.5,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 125,
    "Cholesterol (mg)": 43,
    "Dietary Fibre (g)": 2,
    "Sugars (g)": 34,
    "Protein (g)": 13,
    "Vitamin A (fDV)": 0.2,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.35,
    "Iron (fDV)": 0.25,
    "Caffeine (mg)": 175
  },
  {
    "Beverage_category": "Classic Espresso Drinks",
    "Beverage": "Caff̬ Mocha (Without Whipped Cream)",
    "Beverage_prep": "2% Milk",
    "Calories": 260,
    "Total Fat (g)": 8,
    "Trans Fat (g)": 4.5,
    "Saturated Fat (g)": 0.2,
    "Sodium (mg)": 25,
    "Total Carbohydrates (g)": 140,
    "Cholesterol (mg)": 42,
    "Dietary Fibre (g)": 2,
    "Sugars (g)": 34,
    "Protein (g)": 13,
    "Vitamin A (fDV)": 0.15,
    "Vitamin C (fDV)": 0.02,
    "Calcium (fDV)": 0.35,
    "Iron (fDV)": 0.25,
    "Caffeine (mg)": 175
  },
  {
    "Beverage_category": "Classic Espresso Drinks",
    "Beverage": "Caff̬ Mocha (Without Whipped Cream)",
    "Beverage_prep": "Soymilk",
    "Calories": 230,
    "Total Fat (g)": 7,
    "Trans Fat (g)": 2,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 105,
    "Cholesterol (mg)": 37,
    "Dietary Fibre (g)": 3,
    "Sugars (g)": 26,
    "Protein (g)": 11,
    "Vitamin A (fDV)": 0.1,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.35,
    "Iron (fDV)": 0.4,
    "Caffeine (mg)": 175
  },
  {
    "Beverage_category": "Classic Espresso Drinks",
    "Beverage": "Vanilla Latte (Or Other Flavoured Latte)",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 200,
    "Total Fat (g)": 0.3,
    "Trans Fat (g)": 0.2,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 140,
    "Cholesterol (mg)": 37,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 35,
    "Protein (g)": 12,
    "Vitamin A (fDV)": 0.2,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.35,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 150
  },
  {
    "Beverage_category": "Classic Espresso Drinks",
    "Beverage": "Vanilla Latte (Or Other Flavoured Latte)",
    "Beverage_prep": "2% Milk",
    "Calories": 250,
    "Total Fat (g)": 6,
    "Trans Fat (g)": 3.5,
    "Saturated Fat (g)": 0.2,
    "Sodium (mg)": 25,
    "Total Carbohydrates (g)": 150,
    "Cholesterol (mg)": 37,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 35,
    "Protein (g)": 12,
    "Vitamin A (fDV)": 0.2,
    "Vitamin C (fDV)": 0.02,
    "Calcium (fDV)": 0.35,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 150
  },
  {
    "Beverage_category": "Classic Espresso Drinks",
    "Beverage": "Vanilla Latte (Or Other Flavoured Latte)",
    "Beverage_prep": "Soymilk",
    "Calories": 210,
    "Total Fat (g)": 5,
    "Trans Fat (g)": 0.5,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 120,
    "Cholesterol (mg)": 31,
    "Dietary Fibre (g)": 1,
    "Sugars (g)": 26,
    "Protein (g)": 9,
    "Vitamin A (fDV)": 0.1,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.35,
    "Iron (fDV)": 0.15,
    "Caffeine (mg)": 150
  },
  {
    "Beverage_category": "Classic Espresso Drinks",
    "Beverage": "Caff̬ Americano",
    "Beverage_prep": "Plain",
    "Calories": 15,
    "Total Fat (g)": 0,
    "Trans Fat (g)": 0,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 15,
    "Cholesterol (mg)": 3,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 0,
    "Protein (g)": 1,
    "Vitamin A (fDV)": 0,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.02,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 225
  },
  {
    "Beverage_category": "Classic Espresso Drinks",
    "Beverage": "Cappuccino",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 80,
    "Total Fat (g)": 0.2,
    "Trans Fat (g)": 0.1,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 90,
    "Cholesterol (mg)": 12,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 10,
    "Protein (g)": 8,
    "Vitamin A (fDV)": 0.15,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.25,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 150
  },
  {
    "Beverage_category": "Classic Espresso Drinks",
    "Beverage": "Cappuccino",
    "Beverage_prep": "2% Milk",
    "Calories": 120,
    "Total Fat (g)": 4,
    "Trans Fat (g)": 2,
    "Saturated Fat (g)": 0.1,
    "Sodium (mg)": 15,
    "Total Carbohydrates (g)": 100,
    "Cholesterol (mg)": 12,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 10,
    "Protein (g)": 8,
    "Vitamin A (fDV)": 0.1,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.25,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 150
  },
  {
    "Beverage_category": "Classic Espresso Drinks",
    "Beverage": "Cappuccino",
    "Beverage_prep": "Soymilk",
    "Calories": 100,
    "Total Fat (g)": 3.5,
    "Trans Fat (g)": 0.4,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 80,
    "Cholesterol (mg)": 9,
    "Dietary Fibre (g)": 1,
    "Sugars (g)": 5,
    "Protein (g)": 7,
    "Vitamin A (fDV)": 0.08,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.25,
    "Iron (fDV)": 0.1,
    "Caffeine (mg)": 150
  },
  {
    "Beverage_category": "Classic Espresso Drinks",
    "Beverage": "Skinny Latte (Any Flavour)",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 120,
    "Total Fat (g)": 0.3,
    "Trans Fat (g)": 0.2,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 160,
    "Cholesterol (mg)": 18,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 16,
    "Protein (g)": 12,
    "Vitamin A (fDV)": 0.2,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.35,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 150
  },
  {
    "Beverage_category": "Signature Espresso Drinks",
    "Beverage": "Caramel Macchiato",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 190,
    "Total Fat (g)": 1,
    "Trans Fat (g)": 1,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 10,
    "Total Carbohydrates (g)": 130,
    "Cholesterol (mg)": 35,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 32,
    "Protein (g)": 11,
    "Vitamin A (fDV)": 0.2,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.35,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 150
  },
  {
    "Beverage_category": "Signature Espresso Drinks",
    "Beverage": "Caramel Macchiato",
    "Beverage_prep": "2% Milk",
    "Calories": 240,
    "Total Fat (g)": 7,
    "Trans Fat (g)": 3.5,
    "Saturated Fat (g)": 0.2,
    "Sodium (mg)": 25,
    "Total Carbohydrates (g)": 150,
    "Cholesterol (mg)": 34,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 32,
    "Protein (g)": 10,
    "Vitamin A (fDV)": 0.15,
    "Vitamin C (fDV)": 0.02,
    "Calcium (fDV)": 0.3,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 150
  },
  {
    "Beverage_category": "Signature Espresso Drinks",
    "Beverage": "Caramel Macchiato",
    "Beverage_prep": "Soymilk",
    "Calories": 200,
    "Total Fat (g)": 5,
    "Trans Fat (g)": 1,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 115,
    "Cholesterol (mg)": 29,
    "Dietary Fibre (g)": 1,
    "Sugars (g)": 24,
    "Protein (g)": 9,
    "Vitamin A (fDV)": 0.1,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.35,
    "Iron (fDV)": 0.15,
    "Caffeine (mg)": 150
  },
  {
    "Beverage_category": "Signature Espresso Drinks",
    "Beverage": "White Chocolate Mocha (Without Whipped Cream)",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 350,
    "Total Fat (g)": 6,
    "Trans Fat (g)": 4.5,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 10,
    "Total Carbohydrates (g)": 240,
    "Cholesterol (mg)": 61,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 58,
    "Protein (g)": 15,
    "Vitamin A (fDV)": 0.2,
    "Vitamin C (fDV)": 0.02,
    "Calcium (fDV)": 0.45,
    "Iron (fDV)": 0.02,
    "Caffeine (mg)": 150
  },
  {
    "Beverage_category": "Signature Espresso Drinks",
    "Beverage": "White Chocolate Mocha (Without Whipped Cream)",
    "Beverage_prep": "2% Milk",
    "Calories": 400,
    "Total Fat (g)": 11,
    "Trans Fat (g)": 7,
    "Saturated Fat (g)": 0.2,
    "Sodium (mg)": 25,
    "Total Carbohydrates (g)": 250,
    "Cholesterol (mg)": 61,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 58,
    "Protein (g)": 15,
    "Vitamin A (fDV)": 0.15,
    "Vitamin C (fDV)": 0.02,
    "Calcium (fDV)": 0.45,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 150
  },
  {
    "Beverage_category": "Signature Espresso Drinks",
    "Beverage": "White Chocolate Mocha (Without Whipped Cream)",
    "Beverage_prep": "Soymilk",
    "Calories": 370,
    "Total Fat (g)": 10,
    "Trans Fat (g)": 5,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 220,
    "Cholesterol (mg)": 56,
    "Dietary Fibre (g)": 1,
    "Sugars (g)": 51,
    "Protein (g)": 13,
    "Vitamin A (fDV)": 0.1,
    "Vitamin C (fDV)": 0.02,
    "Calcium (fDV)": 0.45,
    "Iron (fDV)": 0.15,
    "Caffeine (mg)": 150
  },
  {
    "Beverage_category": "Signature Espresso Drinks",
    "Beverage": "Hot Chocolate (Without Whipped Cream)",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 240,
    "Total Fat (g)": 2.5,
    "Trans Fat (g)": 1.5,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 140,
    "Cholesterol (mg)": 48,
    "Dietary Fibre (g)": 2,
    "Sugars (g)": 41,
    "Protein (g)": 14,
    "Vitamin A (fDV)": 0.2,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.4,
    "Iron (fDV)": 0.25,
    "Caffeine (mg)": 25
  },
  {
    "Beverage_category": "Signature Espresso Drinks",
    "Beverage": "Hot Chocolate (Without Whipped Cream)",
    "Beverage_prep": "2% Milk",
    "Calories": 290,
    "Total Fat (g)": 9,
    "Trans Fat (g)": 5,
    "Saturated Fat (g)": 0.2,
    "Sodium (mg)": 25,
    "Total Carbohydrates (g)": 160,
    "Cholesterol (mg)": 47,
    "Dietary Fibre (g)": 2,
    "Sugars (g)": 41,
    "Protein (g)": 14,
    "Vitamin A (fDV)": 0.2,
    "Vitamin C (fDV)": 0.02,
    "Calcium (fDV)": 0.4,
    "Iron (fDV)": 0.25,
    "Caffeine (mg)": 25
  },
  {
    "Beverage_category": "Signature Espresso Drinks",
    "Beverage": "Hot Chocolate (Without Whipped Cream)",
    "Beverage_prep": "Soymilk",
    "Calories": 250,
    "Total Fat (g)": 7,
    "Trans Fat (g)": 2,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 125,
    "Cholesterol (mg)": 41,
    "Dietary Fibre (g)": 3,
    "Sugars (g)": 32,
    "Protein (g)": 12,
    "Vitamin A (fDV)": 0.15,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.4,
    "Iron (fDV)": 0.4,
    "Caffeine (mg)": 25
  },
  {
    "Beverage_category": "Signature Espresso Drinks",
    "Beverage": "Caramel Apple Spice (Without Whipped Cream)",
    "Beverage_prep": "Plain",
    "Calories": 280,
    "Total Fat (g)": 0,
    "Trans Fat (g)": 0,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 20,
    "Cholesterol (mg)": 70,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 65,
    "Protein (g)": 0,
    "Vitamin A (fDV)": 0,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 0
  },
  {
    "Beverage_category": "Tazo� Tea Drinks",
    "Beverage": "Tazo� Tea",
    "Beverage_prep": "Plain",
    "Calories": 0,
    "Total Fat (g)": 0,
    "Trans Fat (g)": 0,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 0,
    "Cholesterol (mg)": 0,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 0,
    "Protein (g)": 0,
    "Vitamin A (fDV)": 0,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 95
  },
  {
    "Beverage_category": "Tazo� Tea Drinks",
    "Beverage": "Tazo� Chai Tea Latte",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 210,
    "Total Fat (g)": 0.2,
    "Trans Fat (g)": 0.1,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 105,
    "Cholesterol (mg)": 45,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 43,
    "Protein (g)": 8,
    "Vitamin A (fDV)": 0.15,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.25,
    "Iron (fDV)": 0.02,
    "Caffeine (mg)": 95
  },
  {
    "Beverage_category": "Tazo� Tea Drinks",
    "Beverage": "Tazo� Chai Tea Latte",
    "Beverage_prep": "2% Milk",
    "Calories": 240,
    "Total Fat (g)": 4.5,
    "Trans Fat (g)": 2,
    "Saturated Fat (g)": 0.1,
    "Sodium (mg)": 20,
    "Total Carbohydrates (g)": 115,
    "Cholesterol (mg)": 45,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 42,
    "Protein (g)": 8,
    "Vitamin A (fDV)": 0.1,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.25,
    "Iron (fDV)": 0.02,
    "Caffeine (mg)": 95
  },
  {
    "Beverage_category": "Tazo� Tea Drinks",
    "Beverage": "Tazo� Chai Tea Latte",
    "Beverage_prep": "Soymilk",
    "Calories": 220,
    "Total Fat (g)": 3.5,
    "Trans Fat (g)": 0.4,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 90,
    "Cholesterol (mg)": 41,
    "Dietary Fibre (g)": 1,
    "Sugars (g)": 37,
    "Protein (g)": 6,
    "Vitamin A (fDV)": 0.08,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.25,
    "Iron (fDV)": 0.1,
    "Caffeine (mg)": 95
  },
  {
    "Beverage_category": "Tazo� Tea Drinks",
    "Beverage": "Tazo� Green Tea Latte",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 290,
    "Total Fat (g)": 0.5,
    "Trans Fat (g)": 0.2,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 10,
    "Total Carbohydrates (g)": 160,
    "Cholesterol (mg)": 57,
    "Dietary Fibre (g)": 1,
    "Sugars (g)": 56,
    "Protein (g)": 14,
    "Vitamin A (fDV)": 0.25,
    "Vitamin C (fDV)": 0.15,
    "Calcium (fDV)": 0.45,
    "Iron (fDV)": 0.04,
    "Caffeine (mg)": 80
  },
  {
    "Beverage_category": "Tazo� Tea Drinks",
    "Beverage": "Tazo� Green Tea Latte",
    "Beverage_prep": "2% Milk",
    "Calories": 350,
    "Total Fat (g)": 8,
    "Trans Fat (g)": 4,
    "Saturated Fat (g)": 0.2,
    "Sodium (mg)": 30,
    "Total Carbohydrates (g)": 180,
    "Cholesterol (mg)": 57,
    "Dietary Fibre (g)": 1,
    "Sugars (g)": 55,
    "Protein (g)": 14,
    "Vitamin A (fDV)": 0.2,
    "Vitamin C (fDV)": 0.15,
    "Calcium (fDV)": 0.45,
    "Iron (fDV)": 0.04,
    "Caffeine (mg)": 80
  },
  {
    "Beverage_category": "Tazo� Tea Drinks",
    "Beverage": "Tazo� Green Tea Latte",
    "Beverage_prep": "Soymilk",
    "Calories": 310,
    "Total Fat (g)": 6,
    "Trans Fat (g)": 1,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 140,
    "Cholesterol (mg)": 50,
    "Dietary Fibre (g)": 3,
    "Sugars (g)": 46,
    "Protein (g)": 11,
    "Vitamin A (fDV)": 0.15,
    "Vitamin C (fDV)": 0.15,
    "Calcium (fDV)": 0.45,
    "Iron (fDV)": 0.25,
    "Caffeine (mg)": 80
  },
  {
    "Beverage_category": "Tazo� Tea Drinks",
    "Beverage": "Tazo� Full-Leaf Tea Latte",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 150,
    "Total Fat (g)": 0.2,
    "Trans Fat (g)": 0.1,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 85,
    "Cholesterol (mg)": 31,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 31,
    "Protein (g)": 7,
    "Vitamin A (fDV)": 0.15,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.25,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 120
  },
  {
    "Beverage_category": "Tazo� Tea Drinks",
    "Beverage": "Tazo� Full-Leaf Tea Latte",
    "Beverage_prep": "2% Milk",
    "Calories": 190,
    "Total Fat (g)": 4,
    "Trans Fat (g)": 2,
    "Saturated Fat (g)": 0.1,
    "Sodium (mg)": 15,
    "Total Carbohydrates (g)": 95,
    "Cholesterol (mg)": 31,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 30,
    "Protein (g)": 7,
    "Vitamin A (fDV)": 0.1,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.25,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 120
  },
  {
    "Beverage_category": "Tazo� Tea Drinks",
    "Beverage": "Tazo� Full-Leaf Tea Latte",
    "Beverage_prep": "Soymilk",
    "Calories": 170,
    "Total Fat (g)": 3.5,
    "Trans Fat (g)": 0.4,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 80,
    "Cholesterol (mg)": 27,
    "Dietary Fibre (g)": 1,
    "Sugars (g)": 25,
    "Protein (g)": 6,
    "Vitamin A (fDV)": 0.08,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.25,
    "Iron (fDV)": 0.1,
    "Caffeine (mg)": 120
  },
  {
    "Beverage_category": "Tazo� Tea Drinks",
    "Beverage": "Tazo� Full-Leaf Red Tea Latte (Vanilla Rooibos)",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 150,
    "Total Fat (g)": 0.2,
    "Trans Fat (g)": 0.1,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 85,
    "Cholesterol (mg)": 31,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 31,
    "Protein (g)": 7,
    "Vitamin A (fDV)": 0.15,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.25,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 0
  },
  {
    "Beverage_category": "Tazo� Tea Drinks",
    "Beverage": "Tazo� Full-Leaf Red Tea Latte (Vanilla Rooibos)",
    "Beverage_prep": "2% Milk",
    "Calories": 190,
    "Total Fat (g)": 4,
    "Trans Fat (g)": 2,
    "Saturated Fat (g)": 0.1,
    "Sodium (mg)": 15,
    "Total Carbohydrates (g)": 95,
    "Cholesterol (mg)": 31,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 30,
    "Protein (g)": 7,
    "Vitamin A (fDV)": 0.1,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.25,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 0
  },
  {
    "Beverage_category": "Tazo� Tea Drinks",
    "Beverage": "Tazo� Full-Leaf Red Tea Latte (Vanilla Rooibos)",
    "Beverage_prep": "Soymilk",
    "Calories": 170,
    "Total Fat (g)": 3.5,
    "Trans Fat (g)": 0.4,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 80,
    "Cholesterol (mg)": 27,
    "Dietary Fibre (g)": 1,
    "Sugars (g)": 25,
    "Protein (g)": 6,
    "Vitamin A (fDV)": 0.08,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.25,
    "Iron (fDV)": 0.1,
    "Caffeine (mg)": 0
  },
  {
    "Beverage_category": "Shaken Iced Beverages",
    "Beverage": "Iced Brewed Coffee (With Classic Syrup)",
    "Beverage_prep": "Plain",
    "Calories": 90,
    "Total Fat (g)": 0.1,
    "Trans Fat (g)": 0,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 5,
    "Cholesterol (mg)": 21,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 21,
    "Protein (g)": 0.3,
    "Vitamin A (fDV)": 0,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 165
  },
  {
    "Beverage_category": "Shaken Iced Beverages",
    "Beverage": "Iced Brewed Coffee (With Milk & Classic Syrup)",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 110,
    "Total Fat (g)": 0.1,
    "Trans Fat (g)": 0,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 30,
    "Cholesterol (mg)": 24,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 24,
    "Protein (g)": 2,
    "Vitamin A (fDV)": 0.04,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.08,
    "Iron (fDV)": 0.02,
    "Caffeine (mg)": 90
  },
  {
    "Beverage_category": "Shaken Iced Beverages",
    "Beverage": "Iced Brewed Coffee (With Milk & Classic Syrup)",
    "Beverage_prep": "2% Milk",
    "Calories": 120,
    "Total Fat (g)": 1.5,
    "Trans Fat (g)": 0.5,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 35,
    "Cholesterol (mg)": 24,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 24,
    "Protein (g)": 2,
    "Vitamin A (fDV)": 0.04,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.08,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 125
  },
  {
    "Beverage_category": "Shaken Iced Beverages",
    "Beverage": "Iced Brewed Coffee (With Milk & Classic Syrup)",
    "Beverage_prep": "Soymilk",
    "Calories": 110,
    "Total Fat (g)": 1,
    "Trans Fat (g)": 0.1,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 30,
    "Cholesterol (mg)": 23,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 22,
    "Protein (g)": 2,
    "Vitamin A (fDV)": 0.02,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.08,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 125
  },
  {
    "Beverage_category": "Shaken Iced Beverages",
    "Beverage": "Shaken Iced Tazo� Tea (With Classic Syrup)",
    "Beverage_prep": "Plain",
    "Calories": 80,
    "Total Fat (g)": 0,
    "Trans Fat (g)": 0,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 0,
    "Cholesterol (mg)": 21,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 21,
    "Protein (g)": 0,
    "Vitamin A (fDV)": 0,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 100
  },
  {
    "Beverage_category": "Shaken Iced Beverages",
    "Beverage": "Shaken Iced Tazo� Tea Lemonade (With Classic Syrup)",
    "Beverage_prep": "Plain",
    "Calories": 130,
    "Total Fat (g)": 0,
    "Trans Fat (g)": 0,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 0,
    "Cholesterol (mg)": 33,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 33,
    "Protein (g)": 0.1,
    "Vitamin A (fDV)": 0,
    "Vitamin C (fDV)": 0.15,
    "Calcium (fDV)": 0,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 100
  },
  {
    "Beverage_category": "Smoothies",
    "Beverage": "Banana Chocolate Smoothie",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 280,
    "Total Fat (g)": 2.5,
    "Trans Fat (g)": 1.5,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 150,
    "Cholesterol (mg)": 53,
    "Dietary Fibre (g)": 7,
    "Sugars (g)": 34,
    "Protein (g)": 20,
    "Vitamin A (fDV)": 0.1,
    "Vitamin C (fDV)": 0.15,
    "Calcium (fDV)": 0.2,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 100
  },
  {
    "Beverage_category": "Smoothies",
    "Beverage": "Banana Chocolate Smoothie",
    "Beverage_prep": "2% Milk",
    "Calories": 300,
    "Total Fat (g)": 5,
    "Trans Fat (g)": 2.5,
    "Saturated Fat (g)": 0.1,
    "Sodium (mg)": 15,
    "Total Carbohydrates (g)": 160,
    "Cholesterol (mg)": 53,
    "Dietary Fibre (g)": 7,
    "Sugars (g)": 34,
    "Protein (g)": 20,
    "Vitamin A (fDV)": 0.08,
    "Vitamin C (fDV)": 0.15,
    "Calcium (fDV)": 0.2,
    "Iron (fDV)": 0.2,
    "Caffeine (mg)": 15
  },
  {
    "Beverage_category": "Smoothies",
    "Beverage": "Banana Chocolate Smoothie",
    "Beverage_prep": "Soymilk",
    "Calories": 290,
    "Total Fat (g)": 4.5,
    "Trans Fat (g)": 1.5,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 150,
    "Cholesterol (mg)": 51,
    "Dietary Fibre (g)": 7,
    "Sugars (g)": 31,
    "Protein (g)": 19,
    "Vitamin A (fDV)": 0.06,
    "Vitamin C (fDV)": 0.15,
    "Calcium (fDV)": 0.2,
    "Iron (fDV)": 0.2,
    "Caffeine (mg)": 15
  },
  {
    "Beverage_category": "Smoothies",
    "Beverage": "Orange Mango Banana Smoothie",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 260,
    "Total Fat (g)": 1,
    "Trans Fat (g)": 0.3,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 120,
    "Cholesterol (mg)": 54,
    "Dietary Fibre (g)": 6,
    "Sugars (g)": 37,
    "Protein (g)": 16,
    "Vitamin A (fDV)": 0.5,
    "Vitamin C (fDV)": 0.8,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0.3,
    "Caffeine (mg)": 15
  },
  {
    "Beverage_category": "Smoothies",
    "Beverage": "Orange Mango Banana Smoothie",
    "Beverage_prep": "2% Milk",
    "Calories": 270,
    "Total Fat (g)": 1.5,
    "Trans Fat (g)": 0.5,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 125,
    "Cholesterol (mg)": 53,
    "Dietary Fibre (g)": 6,
    "Sugars (g)": 37,
    "Protein (g)": 16,
    "Vitamin A (fDV)": 0.5,
    "Vitamin C (fDV)": 0.8,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0.06,
    "Caffeine (mg)": 0
  },
  {
    "Beverage_category": "Smoothies",
    "Beverage": "Orange Mango Banana Smoothie",
    "Beverage_prep": "Soymilk",
    "Calories": 270,
    "Total Fat (g)": 1.5,
    "Trans Fat (g)": 0.4,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 120,
    "Cholesterol (mg)": 53,
    "Dietary Fibre (g)": 6,
    "Sugars (g)": 36,
    "Protein (g)": 15,
    "Vitamin A (fDV)": 0.5,
    "Vitamin C (fDV)": 0.8,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0.06,
    "Caffeine (mg)": 0
  },
  {
    "Beverage_category": "Smoothies",
    "Beverage": "Strawberry Banana Smoothie",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 290,
    "Total Fat (g)": 1,
    "Trans Fat (g)": 0.3,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 125,
    "Cholesterol (mg)": 58,
    "Dietary Fibre (g)": 7,
    "Sugars (g)": 41,
    "Protein (g)": 16,
    "Vitamin A (fDV)": 0.04,
    "Vitamin C (fDV)": 1,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0.08,
    "Caffeine (mg)": 0
  },
  {
    "Beverage_category": "Smoothies",
    "Beverage": "Strawberry Banana Smoothie",
    "Beverage_prep": "2% Milk",
    "Calories": 290,
    "Total Fat (g)": 2,
    "Trans Fat (g)": 1,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 125,
    "Cholesterol (mg)": 58,
    "Dietary Fibre (g)": 7,
    "Sugars (g)": 41,
    "Protein (g)": 16,
    "Vitamin A (fDV)": 0.04,
    "Vitamin C (fDV)": 1,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0.08,
    "Caffeine (mg)": 0
  },
  {
    "Beverage_category": "Smoothies",
    "Beverage": "Strawberry Banana Smoothie",
    "Beverage_prep": "Soymilk",
    "Calories": 290,
    "Total Fat (g)": 2,
    "Trans Fat (g)": 0.4,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 120,
    "Cholesterol (mg)": 58,
    "Dietary Fibre (g)": 8,
    "Sugars (g)": 40,
    "Protein (g)": 16,
    "Vitamin A (fDV)": 0.02,
    "Vitamin C (fDV)": 1,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0.08,
    "Caffeine (mg)": 0
  },
  {
    "Beverage_category": "Frappuccino� Blended Coffee",
    "Beverage": "Coffee",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 220,
    "Total Fat (g)": 0.1,
    "Trans Fat (g)": 0.1,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 210,
    "Cholesterol (mg)": 51,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 50,
    "Protein (g)": 4,
    "Vitamin A (fDV)": 0.06,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0.04,
    "Caffeine (mg)": 70
  },
  {
    "Beverage_category": "Frappuccino� Blended Coffee",
    "Beverage": "Coffee",
    "Beverage_prep": "Whole Milk",
    "Calories": 240,
    "Total Fat (g)": 3,
    "Trans Fat (g)": 2,
    "Saturated Fat (g)": 0.1,
    "Sodium (mg)": 10,
    "Total Carbohydrates (g)": 220,
    "Cholesterol (mg)": 50,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 50,
    "Protein (g)": 3,
    "Vitamin A (fDV)": 0.04,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 95
  },
  {
    "Beverage_category": "Frappuccino� Blended Coffee",
    "Beverage": "Coffee",
    "Beverage_prep": "Soymilk",
    "Calories": 220,
    "Total Fat (g)": 1.5,
    "Trans Fat (g)": 0.2,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 210,
    "Cholesterol (mg)": 49,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 47,
    "Protein (g)": 3,
    "Vitamin A (fDV)": 0.04,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 95
  },
  {
    "Beverage_category": "Frappuccino� Blended Coffee",
    "Beverage": "Mocha (Without Whipped Cream)",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 260,
    "Total Fat (g)": 1,
    "Trans Fat (g)": 0.5,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 220,
    "Cholesterol (mg)": 61,
    "Dietary Fibre (g)": 1,
    "Sugars (g)": 58,
    "Protein (g)": 4,
    "Vitamin A (fDV)": 0.06,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0.08,
    "Caffeine (mg)": 110
  },
  {
    "Beverage_category": "Frappuccino� Blended Coffee",
    "Beverage": "Mocha (Without Whipped Cream)",
    "Beverage_prep": "Whole Milk",
    "Calories": 290,
    "Total Fat (g)": 4,
    "Trans Fat (g)": 2.5,
    "Saturated Fat (g)": 0.1,
    "Sodium (mg)": 10,
    "Total Carbohydrates (g)": 220,
    "Cholesterol (mg)": 61,
    "Dietary Fibre (g)": 1,
    "Sugars (g)": 58,
    "Protein (g)": 4,
    "Vitamin A (fDV)": 0.04,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0.08,
    "Caffeine (mg)": 110
  },
  {
    "Beverage_category": "Frappuccino� Blended Coffee",
    "Beverage": "Mocha (Without Whipped Cream)",
    "Beverage_prep": "Soymilk",
    "Calories": 260,
    "Total Fat (g)": 2.5,
    "Trans Fat (g)": 0.5,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 220,
    "Cholesterol (mg)": 59,
    "Dietary Fibre (g)": 1,
    "Sugars (g)": 55,
    "Protein (g)": 4,
    "Vitamin A (fDV)": 0.04,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0.15,
    "Caffeine (mg)": 110
  },
  {
    "Beverage_category": "Frappuccino� Blended Coffee",
    "Beverage": "Caramel (Without Whipped Cream)",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 280,
    "Total Fat (g)": 0.1,
    "Trans Fat (g)": 0.1,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 220,
    "Cholesterol (mg)": 60,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 59,
    "Protein (g)": 4,
    "Vitamin A (fDV)": 0.06,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 100
  },
  {
    "Beverage_category": "Frappuccino� Blended Coffee",
    "Beverage": "Caramel (Without Whipped Cream)",
    "Beverage_prep": "Whole Milk",
    "Calories": 280,
    "Total Fat (g)": 3.5,
    "Trans Fat (g)": 2,
    "Saturated Fat (g)": 0.1,
    "Sodium (mg)": 10,
    "Total Carbohydrates (g)": 220,
    "Cholesterol (mg)": 60,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 59,
    "Protein (g)": 3,
    "Vitamin A (fDV)": 0.04,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 100
  },
  {
    "Beverage_category": "Frappuccino� Blended Coffee",
    "Beverage": "Caramel (Without Whipped Cream)",
    "Beverage_prep": "Soymilk",
    "Calories": 260,
    "Total Fat (g)": 1.5,
    "Trans Fat (g)": 0.2,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 220,
    "Cholesterol (mg)": 58,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 56,
    "Protein (g)": 3,
    "Vitamin A (fDV)": 0.04,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0.06,
    "Caffeine (mg)": 100
  },
  {
    "Beverage_category": "Frappuccino� Blended Coffee",
    "Beverage": "Java Chip (Without Whipped Cream)",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 310,
    "Total Fat (g)": 4,
    "Trans Fat (g)": 3,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 250,
    "Cholesterol (mg)": 67,
    "Dietary Fibre (g)": 2,
    "Sugars (g)": 62,
    "Protein (g)": 5,
    "Vitamin A (fDV)": 0.06,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0.25,
    "Caffeine (mg)": 110
  },
  {
    "Beverage_category": "Frappuccino� Blended Coffee",
    "Beverage": "Java Chip (Without Whipped Cream)",
    "Beverage_prep": "Whole Milk",
    "Calories": 340,
    "Total Fat (g)": 7,
    "Trans Fat (g)": 5,
    "Saturated Fat (g)": 0.1,
    "Sodium (mg)": 10,
    "Total Carbohydrates (g)": 250,
    "Cholesterol (mg)": 67,
    "Dietary Fibre (g)": 2,
    "Sugars (g)": 62,
    "Protein (g)": 5,
    "Vitamin A (fDV)": 0.04,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0.25,
    "Caffeine (mg)": 110
  },
  {
    "Beverage_category": "Frappuccino� Blended Coffee",
    "Beverage": "Java Chip (Without Whipped Cream)",
    "Beverage_prep": "Soymilk",
    "Calories": 310,
    "Total Fat (g)": 6,
    "Trans Fat (g)": 3.5,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 240,
    "Cholesterol (mg)": 65,
    "Dietary Fibre (g)": 2,
    "Sugars (g)": 60,
    "Protein (g)": 4,
    "Vitamin A (fDV)": 0.04,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0.3,
    "Caffeine (mg)": 110
  },
  {
    "Beverage_category": "Frappuccino� Light Blended Coffee",
    "Beverage": "Coffee",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 120,
    "Total Fat (g)": 0.1,
    "Trans Fat (g)": 0.1,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 210,
    "Cholesterol (mg)": 26,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 26,
    "Protein (g)": 3,
    "Vitamin A (fDV)": 0.06,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 95
  },
  {
    "Beverage_category": "Frappuccino� Light Blended Coffee",
    "Beverage": "Mocha",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 150,
    "Total Fat (g)": 1,
    "Trans Fat (g)": 0.5,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 200,
    "Cholesterol (mg)": 33,
    "Dietary Fibre (g)": 1,
    "Sugars (g)": 30,
    "Protein (g)": 4,
    "Vitamin A (fDV)": 0.06,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0.08,
    "Caffeine (mg)": 95
  },
  {
    "Beverage_category": "Frappuccino� Light Blended Coffee",
    "Beverage": "Caramel",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 150,
    "Total Fat (g)": 0.1,
    "Trans Fat (g)": 0.1,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 200,
    "Cholesterol (mg)": 33,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 32,
    "Protein (g)": 3,
    "Vitamin A (fDV)": 0.06,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 90
  },
  {
    "Beverage_category": "Frappuccino� Light Blended Coffee",
    "Beverage": "Java Chip",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 220,
    "Total Fat (g)": 4,
    "Trans Fat (g)": 3,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 240,
    "Cholesterol (mg)": 43,
    "Dietary Fibre (g)": 2,
    "Sugars (g)": 39,
    "Protein (g)": 5,
    "Vitamin A (fDV)": 0.06,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.1,
    "Iron (fDV)": 0.25,
    "Caffeine (mg)": 105
  },
  {
    "Beverage_category": "Frappuccino� Blended Cr̬me",
    "Beverage": "Strawberries & Cr̬me (Without Whipped Cream)",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 230,
    "Total Fat (g)": 0.2,
    "Trans Fat (g)": 0.1,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 190,
    "Cholesterol (mg)": 53,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 52,
    "Protein (g)": 4,
    "Vitamin A (fDV)": 0.08,
    "Vitamin C (fDV)": 0.06,
    "Calcium (fDV)": 0.15,
    "Iron (fDV)": 0.04,
    "Caffeine (mg)": 0
  },
  {
    "Beverage_category": "Frappuccino� Blended Cr̬me",
    "Beverage": "Strawberries & Cr̬me (Without Whipped Cream)",
    "Beverage_prep": "Whole Milk",
    "Calories": 260,
    "Total Fat (g)": 4,
    "Trans Fat (g)": 2,
    "Saturated Fat (g)": 0.1,
    "Sodium (mg)": 10,
    "Total Carbohydrates (g)": 190,
    "Cholesterol (mg)": 53,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 52,
    "Protein (g)": 4,
    "Vitamin A (fDV)": 0.06,
    "Vitamin C (fDV)": 0.06,
    "Calcium (fDV)": 0.15,
    "Iron (fDV)": 0.04,
    "Caffeine (mg)": 0
  },
  {
    "Beverage_category": "Frappuccino� Blended Cr̬me",
    "Beverage": "Strawberries & Cr̬me (Without Whipped Cream)",
    "Beverage_prep": "Soymilk",
    "Calories": 240,
    "Total Fat (g)": 2,
    "Trans Fat (g)": 0.2,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 0,
    "Total Carbohydrates (g)": 180,
    "Cholesterol (mg)": 51,
    "Dietary Fibre (g)": 1,
    "Sugars (g)": 49,
    "Protein (g)": 3,
    "Vitamin A (fDV)": 0.04,
    "Vitamin C (fDV)": 0.06,
    "Calcium (fDV)": 0.15,
    "Iron (fDV)": 0.08,
    "Caffeine (mg)": 0
  },
  {
    "Beverage_category": "Frappuccino� Blended Cr̬me",
    "Beverage": "Vanilla Bean (Without Whipped Cream)",
    "Beverage_prep": "Nonfat Milk",
    "Calories": 240,
    "Total Fat (g)": 0.1,
    "Trans Fat (g)": 0.1,
    "Saturated Fat (g)": 0,
    "Sodium (mg)": 5,
    "Total Carbohydrates (g)": 230,
    "Cholesterol (mg)": 56,
    "Dietary Fibre (g)": 0,
    "Sugars (g)": 55,
    "Protein (g)": 5,
    "Vitamin A (fDV)": 0.08,
    "Vitamin C (fDV)": 0,
    "Calcium (fDV)": 0.15,
    "Iron (fDV)": 0,
    "Caffeine (mg)": 0
  }
];

